adding KeziaA to github
Codubee/StockPickerMW11-12-Back pull request #3
Opened 2021-07-19 22:43 UTC by keziaabraham

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
 This is my first pull request however I had to modify the delete route.

* **What is the current behavior?What does the code do before you made the new changes?** 
It contains 3 routes: post, get, and delete, which allows a person to make changes to the API database.

* **What is the new behavior?**
The delete route is now able to delete a person based on the ID number that is passed as a query parameter.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
This PR does not introduce a breaking change. There are no new commands that need to be run.

* **Other information**:

2021-07-20 16:26 UTC, NathanP9000 commented on KeziaA/index.js
> +    axios.get('http://java-sample-api-2020.herokuapp.com/getAllPeople',body)//gets all the people in the database
When getting people the body parameter is not needed.

2021-07-20 16:28 UTC, NathanP9000 requested changes
Everything looks functional, and the code looks nice, but on line 27 the body parameter should probably be removed as the get request does not need the body.

2021-07-20 17:08 UTC, iakujobi reviewed
- Modify the regular functions to arrow functions in lines 7, 11, 24, 28, 40, and 45. 

- Remove the body parameters in the get and delete routes

2021-07-20 20:36 UTC, sanjanajadhavv commented
The code looks really organized and easy to understand.
- body parameters are only needed in the post route

2021-07-20 20:42 UTC, sanjanajadhavv requested changes

2021-07-20 20:42 UTC, sanjanajadhavv commented on KeziaA/index.js
> +const express = require('express')
The code looks really organized and easy to understand.
- body parameters are only needed in the post route

2021-07-20 20:43 UTC, sanjanajadhavv commented on KeziaA/index.js
> +const express = require('express')
The code looks really organized and easy to understand.
- body parameters are only needed in the post route

2021-07-20 22:43 UTC, NathanP9000 submitted a review, later dismissed
The code looks good now.

2021-07-21 00:27 UTC, iakujobi requested changes
The code is good, but there is just one minor error on lines 43 and 44. They are not aligned properly.

2021-07-21 00:48 UTC, iakujobi approved these changes
Code is ready to be merged. Nice job!

2021-07-21 00:55 UTC, sanjanajadhavv approved these changes
Looks good!

2021-07-26 16:02 UTC, merged